name: Build and Publish Backend Service

on:
  workflow_call:

jobs:
  build-and-publish-backend-service:
    name: Build and Publish Backend Service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: libris-maleficarum-service
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'
          dotnet-quality: 'preview'

      - name: Restore dependencies
        run: dotnet restore LibrisMaleficarum.slnx

      - name: Build solution
        run: dotnet build LibrisMaleficarum.slnx --no-restore --configuration Release

      - name: Run linting (format check)
        run: dotnet format LibrisMaleficarum.slnx --verify-no-changes --no-restore

      - name: Run unit tests
        run: dotnet test LibrisMaleficarum.slnx --no-build --configuration Release --logger "trx;LogFileName=test-results.trx" --logger "GitHubActions" --collect:"XPlat Code Coverage"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: dotnet-test-results
          path: libris-maleficarum-service/**/TestResults

      - name: Publish API
        run: dotnet publish src/Api/LibrisMaleficarum.Api.csproj --no-build --configuration Release --output ./publish/api

      - name: Upload API artifact
        uses: actions/upload-artifact@v6
        with:
          name: libris-maleficarum-api
          path: libris-maleficarum-service/publish/api
