name: Set Build Variables

on:
  workflow_call:
    outputs:
      BUILD_VERSION:
        description: The build version
        value: ${{ jobs.set-build-variables.outputs.build_version }}

jobs:
  set-build-variables:
    name: Set build variables
    runs-on: windows-latest
    outputs:
      build_version: ${{ steps.build_version.outputs.GitVersion_FullSemVer }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.2.1
        with:
          versionSpec: "6.0.x"

      - name: Determine Version
        id: build_version
        uses: gittools/actions/gitversion/execute@v3.2.1
        with:
          useConfigFile: true

      - name: Display FullSemVer
        run: |
          echo "FullSemVer: ${{ steps.build_version.outputs.GitVersion_FullSemVer }}"
